language: ruby

install: skip

script: skip

addons:
  ssh_known_hosts: 18.233.170.146

before_deploy:
  - echo "mais um teste" >> teste.txt
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip
  - echo $DEPLOY_KEY >> chave.pem

deploy:
  provider: script
  skip_cleanup: true
  script: scp -i chave.pem -r dpl_cd_upload ec2-user@18.233.170.146:/home/ec2-user/
  on:
    branch: master