language: ruby

install: skip

script: skip

before_deploy:
  - echo "mais um teste" >> teste.txt
  - zip -r latest *
  - mkdir -p dpl_cd_upload
  - mv latest.zip dpl_cd_upload/latest.zip

deploy:

  - provider: s3
    access_key_id: ASIA27R4PQFKW352L6PE
    secret_access_key: 
      secure: b6dx9Y5NyBWxCI5ak46BCc/Q+zpDyJ5FToB4Xazb
    local_dir: dpl_cd_upload
    skip_cleanup: true
    on: &2
      repo: VictorCampos93/testesci
    bucket: testedataner

  - provider: codedeploy
    access_key_id: ASIA27R4PQFKW352L6PE
    secret_access_key: 
      secure: b6dx9Y5NyBWxCI5ak46BCc/Q+zpDyJ5FToB4Xazb
    bucket: testedataner
    key: latest.zip
    application: CatPartyDemoApplication
    deployment_group: MyDeploymentGroup
    on: *2